#
couchbase.hostname=127.0.0.1
couchbase.bucket=bench
couchbase.scope=bench
couchbase.collection=usertable
couchbase.username=Administrator
couchbase.password=password
#couchbase.ca.cert=/Users/name/cert/ca-cert.pem
#couchbase.client.cert=/Users/name/cert/Administrator.p12
#couchbase.keystore.type=PKCS12
couchbase.storageBackend=couchstore
couchbase.durability=0
couchbase.adhoc=false
couchbase.maxParallelism=0
couchbase.kvEndpoints=4
couchbase.sslMode=true
couchbase.kvTimeout=10
couchbase.connectTimeout=10
couchbase.queryTimeout=75
couchbase.mode=default
couchbase.ttlSeconds=0
couchbase.codec=native
couchbase.debug=false
#capella.project.name=ycsb-capella
#capella.database.name=testdb
#capella.token=
#capella.user.email=test.user@example.com
