#
#
recordcount=1000000
operationcount=10000000
threadcount=256
maxexecutiontime=180
status=true
db=com.codelry.util.ycsb-couchbase.CouchbaseClientBinding
test.setup=com.codelry.util.ycsb-couchbase.CouchbaseTestSetup
test.clean=com.codelry.util.ycsb-couchbase.CouchbaseTestCleanup
